// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdjdzvcwfcdtngknrasp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkamR6dmN3ZmNkdG5na25yYXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNjk5MDYsImV4cCI6MjA4Njg0NTkwNn0.x2rvWV7WP5xlMc2hY4WSLrafcZL45hVEo9T6syl0Du8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});